use std::collections::{HashMap, HashSet};
use anyhow::Result;
use rayon::prelude::*;

use crate::types::{Symbol, NamespaceInfo, ClassInfo, DumpConfig};
use crate::demangler::Demangler;

pub struct NamespaceDetector {
    demangler: Demangler,
}

impl NamespaceDetector {
    pub fn new() -> Self {
        Self {
            demangler: Demangler::new(),
        }
    }

    pub fn detect_namespaces(
        &self,
        symbols: &[Symbol],
        classes: &[ClassInfo],
        config: &DumpConfig,
    ) -> Result<Vec<NamespaceInfo>> {
        let mut namespace_map: HashMap<String, NamespaceInfo> = HashMap::new();
        
        let namespaces_from_symbols: Vec<Option<String>> = symbols.par_iter()
            .map(|s| {
                if config.detect_namespaces {
                    self.demangler.extract_namespace(&s.name)
                } else {
                    None
                }
            })
            .collect();
        
        for ns_opt in namespaces_from_symbols {
            if let Some(ns) = ns_opt {
                self.add_or_create_namespace(&mut namespace_map, &ns);
            }
        }
        
        for class in classes {
            if !class.namespace.is_empty() {
                self.add_or_create_namespace(&mut namespace_map, &class.namespace);
                
                if let Some(info) = namespace_map.get_mut(&class.namespace) {
                    if !info.classes.contains(&class.name) {
                        info.classes.push(class.name.clone());
                    }
                }
            }
        }
        
        self.build_hierarchy(&mut namespace_map);
        
        let mut namespaces: Vec<NamespaceInfo> = namespace_map.into_values().collect();
        namespaces.sort_by(|a, b| a.name.cmp(&b.name));
        
        Ok(namespaces)
    }

    fn add_or_create_namespace(
        &self,
        namespace_map: &mut HashMap<String, NamespaceInfo>,
        full_path: &str,
    ) {
        let parts: Vec<&str> = full_path.split("::").collect();
        
        let mut current_path = String::new();
        
        for (i, part) in parts.iter().enumerate() {
            let ns_name = part.to_string();
            
            if i > 0 {
                current_path.push_str("::");
            }
            current_path.push_str(part);
            
            let parent = if i > 0 {
                let parent_parts = &parts[..i];
                Some(parent_parts.join("::"))
            } else {
                None
            };
            
            namespace_map.entry(current_path.clone())
                .or_insert_with(|| NamespaceInfo {
                    name: ns_name.clone(),
                    full_path: current_path.clone(),
                    parent,
                    sub_namespaces: Vec::new(),
                    classes: Vec::new(),
                    functions: Vec::new(),
                });
        }
    }

    fn build_hierarchy(&self, namespace_map: &mut HashMap<String, NamespaceInfo>) {
        let keys: Vec<String> = namespace_map.keys().cloned().collect();
        
        for key in keys {
            if let Some(info) = namespace_map.get(&key) {
                let parent = info.parent.clone();
                let name = info.name.clone();
                
                if let Some(parent_path) = parent {
                    if let Some(parent_info) = namespace_map.get_mut(&parent_path) {
                        if !parent_info.sub_namespaces.contains(&name) {
                            parent_info.sub_namespaces.push(name);
                        }
                    }
                }
            }
        }
    }

    pub fn generate_namespace_cpp(&self, namespaces: &[NamespaceInfo]) -> String {
        let mut output = String::new();
        
        output.push_str("// Lib Dumper - Namespace Reconstruction\n");
        output.push_str("// Generated by Lib Dumper\n\n");
        
        let root_namespaces: Vec<&NamespaceInfo> = namespaces.iter()
            .filter(|ns| ns.parent.is_none())
            .collect();
        
        for ns in root_namespaces {
            self.write_namespace_recursive(&mut output, ns, namespaces, 0);
        }
        
        output
    }

    fn write_namespace_recursive(
        &self,
        output: &mut String,
        ns: &NamespaceInfo,
        all_namespaces: &[NamespaceInfo],
        indent: usize,
    ) {
        let indent_str = "    ".repeat(indent);
        
        output.push_str(&format!("{}namespace {}\n{}{{\n", 
            indent_str, ns.name, indent_str));
        
        for class_name in &ns.classes {
            output.push_str(&format!("{}    class {};\n", indent_str, class_name));
        }
        
        for sub_ns_name in &ns.sub_namespaces {
            if let Some(sub_ns) = all_namespaces.iter().find(|n| &n.name == sub_ns_name) {
                self.write_namespace_recursive(output, sub_ns, all_namespaces, indent + 1);
            }
        }
        
        output.push_str(&format!("{}}}\n\n", indent_str));
    }

    pub fn find_root_namespaces<'a>(&self, namespaces: &'a [NamespaceInfo]) -> Vec<&'a NamespaceInfo> {
        namespaces.iter()
            .filter(|ns| ns.parent.is_none())
            .collect()
    }

    pub fn find_sub_namespaces<'a>(
        &self,
        namespaces: &'a [NamespaceInfo],
        parent_name: &str,
    ) -> Vec<&'a NamespaceInfo> {
        namespaces.iter()
            .filter(|ns| {
                ns.parent.as_deref() == Some(parent_name)
            })
            .collect()
    }

    pub fn get_namespace_depth(&self, full_path: &str) -> usize {
        full_path.split("::").count()
    }

    pub fn get_top_level_namespace(&self, full_path: &str) -> Option<String> {
        full_path.split("::").next().map(|s| s.to_string())
    }
}
